### ISSUE TITLE
`Graph#get_edge_data` doesn't work.

### ISSUE THREAD

**Issue by universato** [SciRuby/networkx.rb#22]
### Description

`Grash#get_edge_data` doesn't work.

```ruby
require 'networkx'

graph = NetworkX::Graph.new
graph.add_nodes(%w[A B])
graph.get_edge_data('A', 'B')
```
↓
```
Traceback (most recent call last):
        2: from sample.rb:5:in `<main>'
        1: from lib/networkx/graph.rb:236:in `get_edge_data'
lib/networkx/graph.rb:212:in `edge?': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

<hr>

- Relevant Issues (optional) : nil
- Relevant PRs (optional) : nil
- Type of issue :
  - User mode :
    - [ ] Installation
    - [ ] Feature request
    - [x] Bug in existing feature
  - Developer mode :
    - [ ] Code quality
    - [ ] Tests
    - [ ] Documentation

**Comment by universato** [comment]
The commit (https://github.com/SciRuby/networkx.rb/commit/af5d69b434778d7da8cff06fa5d40ecd514a699e) resolved this issue.
